<a href="https://colab.research.google.com/github/awgimenes/DEEP_LEARNING_PARA_PROCESSAMENTO_DE_LINGUAGEM_E_VISAO/blob/main/DL_Process_Ling_e_Visao_Tarefa_Trilha4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DEEP LEARNING PARA PROCESSAMENTO DE LINGUAGEM E VISÃO [TURMA 01B]
Tarefa trilha 4 - 
Anderson Willians Gimenes - 10992120393

https://colab.research.google.com/drive/1RH1dJoEnDeYGJ81MZAb_aJALz__XAPv-?usp=sharing


In [ ]:
# Garante que o Colab utilizará o TensorFlow 2.x
%tensorflow_version 2.x
from __future__ import absolute_import, division, print_function, unicode_literals

In [ ]:
import itertools
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import utils
from tensorflow.keras import layers
from tensorflow.keras import models
from tensorflow.keras import datasets
from tensorflow.keras import optimizers

In [ ]:
data = np.load('ORL_faces.npz')

In [ ]:
X_train = data['trainX']
X_train = np.array(X_train, dtype=np.float32)/255

X_test = data['testX']
X_test = np.array(X_test, dtype=np.float32)/255

y_train = data['trainY']
y_test = data['testY']

In [ ]:
# show the train and test Data format
print('X_train : {}'.format(X_train[:]))
print('Y-train shape: {}'.format(y_train))
print('x_test shape: {}'.format(X_test.shape))

X_train : [[0.1882353  0.19215687 0.1764706  ... 0.18431373 0.18039216 0.18039216]
 [0.23529412 0.23529412 0.24313726 ... 0.1254902  0.13333334 0.13333334]
 [0.15294118 0.17254902 0.20784314 ... 0.11372549 0.10196079 0.11372549]
 ...
 [0.44705883 0.45882353 0.44705883 ... 0.38431373 0.3764706  0.38431373]
 [0.4117647  0.4117647  0.41960785 ... 0.21176471 0.18431373 0.16078432]
 [0.45490196 0.44705883 0.45882353 ... 0.37254903 0.39215687 0.39607844]]
Y-train shape: [ 0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1  1  1  1
  2  2  2  2  2  2  2  2  2  2  2  2  3  3  3  3  3  3  3  3  3  3  3  3
  4  4  4  4  4  4  4  4  4  4  4  4  5  5  5  5  5  5  5  5  5  5  5  5
  6  6  6  6  6  6  6  6  6  6  6  6  7  7  7  7  7  7  7  7  7  7  7  7
  8  8  8  8  8  8  8  8  8  8  8  8  9  9  9  9  9  9  9  9  9  9  9  9
 10 10 10 10 10 10 10 10 10 10 10 10 11 11 11 11 11 11 11 11 11 11 11 11
 12 12 12 12 12 12 12 12 12 12 12 12 13 13 13 13 13 13 13 13 13 13 13 13
 14 14 14 14 14 14 1

In [ ]:
X_train, X_valid, y_train, y_valid = train_test_split(X_train, y_train, test_size=.05, random_state=42)

In [ ]:
print(X_train.shape, X_test.shape)

(228, 10304) (160, 10304)


In [ ]:
im_rows = 112
im_cols = 92
im_shape = (im_rows, im_cols, 1)

1. **Reformate** os dados de treinamento, validação e teste no formato adequado para a rede neural.

In [ ]:
# 1. Reformatar os dados de entrada
#change the size of images
X_train = X_train.reshape(X_train.shape[0], *im_shape)
X_test = X_test.reshape(X_test.shape[0], *im_shape)
#X_valid = x_valid.reshape(x_valid.shape[0], *im_shape)

print('x_train shape: {}'.format(X_train.shape))
print('x_test shape: {}'.format(X_test.shape))

x_train shape: (228, 112, 92, 1)
x_test shape: (160, 112, 92, 1)


2. **Construa** a rede neural convolucional objetivando o resultado da métrica apresentado no final deste notebook.

In [ ]:
# 2. Construindo o modelo
model = keras.models.Sequential()
model.add(keras.layers.Conv2D(36, (3, 3), activation='relu', input_shape=(112, 92, 1))) # (image_height, image_width, image_channels)
model.add(keras.layers.MaxPooling2D((2, 2)))
model.add(keras.layers.Conv2D(54, (3, 3), activation='relu'))
model.add(keras.layers.MaxPooling2D((2, 2)))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(2024, activation='relu'))
model.add(keras.layers.Dropout(0.5))
model.add(keras.layers.Dense(1024, activation='relu'))
model.add(keras.layers.Dropout(0.5))
model.add(keras.layers.Dense(512, activation='relu'))
model.add(keras.layers.Dropout(0.5))
model.add(keras.layers.Dense(20, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 110, 90, 36)       360       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 55, 45, 36)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 53, 43, 54)        17550     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 26, 21, 54)       0         
 2D)                                                             
                                                                 
 flatten (Flatten)           (None, 29484)             0         
                                                                 
 dense (Dense)               (None, 2024)              5

3. **Compile** o modelo com os seguintes parâmetros:
* **Loss:** sparse_categorical_entropy;
* **Optimizer:** Adam;
* **Metrics:** accuracy.

In [ ]:
# 3. Compilando o modelo
model.compile(optimizer='Adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

4. **Ajuste** o modelo aos dados de treinamento considerando os seguintes parâmetros:
* batch_size = 512
* verbose = 2

In [ ]:
# 4. Ajustando os modelos aos dados de treinamento
history = model.fit(X_train, y_train, epochs=250, verbose = 2, batch_size=512)

Epoch 1/250
1/1 - 5s - loss: 3.0145 - accuracy: 0.0570 - 5s/epoch - 5s/step
Epoch 2/250
1/1 - 4s - loss: 3.5142 - accuracy: 0.0658 - 4s/epoch - 4s/step
Epoch 3/250
1/1 - 4s - loss: 3.3646 - accuracy: 0.0526 - 4s/epoch - 4s/step
Epoch 4/250
1/1 - 4s - loss: 3.1628 - accuracy: 0.0482 - 4s/epoch - 4s/step
Epoch 5/250
1/1 - 4s - loss: 3.0032 - accuracy: 0.0570 - 4s/epoch - 4s/step
Epoch 6/250
1/1 - 6s - loss: 2.9926 - accuracy: 0.0702 - 6s/epoch - 6s/step
Epoch 7/250
1/1 - 4s - loss: 2.9683 - accuracy: 0.0833 - 4s/epoch - 4s/step
Epoch 8/250
1/1 - 4s - loss: 2.9735 - accuracy: 0.0877 - 4s/epoch - 4s/step
Epoch 9/250
1/1 - 4s - loss: 2.9501 - accuracy: 0.1184 - 4s/epoch - 4s/step
Epoch 10/250
1/1 - 4s - loss: 2.9378 - accuracy: 0.0965 - 4s/epoch - 4s/step
Epoch 11/250
1/1 - 4s - loss: 2.9298 - accuracy: 0.0921 - 4s/epoch - 4s/step
Epoch 12/250
1/1 - 4s - loss: 2.9059 - accuracy: 0.1404 - 4s/epoch - 4s/step
Epoch 13/250
1/1 - 4s - loss: 2.8649 - accuracy: 0.1316 - 4s/epoch - 4s/step
Epoch 14

In [ ]:
# 5. Avaliando o modelo
scor = model.evaluate(X_test, y_test)

print('test los: %.4f'% (scor[0]))
print('test acc: %.2f'% (scor[1]*100),'%')

5/5 [==============================] - 1s 161ms/step - loss: 0.3036 - accuracy: 0.9438
test los: 0.3036
test acc: 94.38 %
